### ISSUE TITLE
Broken links to ontologies

### ISSUE THREAD

**Issue by digitalneoplasm** [OBOFoundry/OBOFoundry.github.io#257]
As of a few minutes ago there are broken links to the following ontologies:
aero, cheminf, chmo, cmf, cvdo, ido, mirano, ncithesaurus, ogg, ogi, ogms, ogsf, rxno, and vto. 

It seems the authors have not updated their purls since the google code shutdown. There are versions of aero, ido, ogg, ogi, ogms, ogsf, and vto available on BioPortal. cheminf, chmo, and rxno are available on their respective github pages. I was unable to find cvdo, mirano, ncithesaurus

For ncithesaurus the issue is more critical - http://www.obofoundry.org/ontology/ncithesaurus.html does not seem to exist. Its website (https://cabig.nci.nih.gov/concepts/EVS/) is also defunct.

**Comment by balhoff** [comment]
I have an SVN checkout of the VTO releases. The files are too big for GitHub. I'll try to get these online elsewhere as soon as possible.

**Comment by cmungall** [comment]
Thanks @digitalneoplasm we're on it

@balhoff if it's individual file size limits you're hitting you could try modularizing, e.g. https://github.com/ontodev/robot/issues/39

**Comment by simonjupp** [comment]
Here are the purls still failing. Is anyone chasing this up? 

chmo - should be https://raw.githubusercontent.com/rsc-ontologies/rsc-cmo/master/chmo.owl
ogg - google code cc @yongqunh 
mop - should redirect to https://raw.githubusercontent.com/rsc-ontologies/rxno/master/mop.owl
cvdi - google code, contact adrien.barton@gmail.com
rxno - should be https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.owl
ido - google code
cheminf - should be https://raw.githubusercontent.com/egonw/semanticchemistry/master/ontology/cheminf.owl
mirnao - google code contact vdritsou@imbb.forth.gr
ogsf - google code

**Comment by yongqunh** [comment]
I am working on OGG…
I guess Asiyah Yu Lin is responsible for OGSF.
Oliver

**Comment by yongqunh** [comment]
Hi Oliver and all,

Thanks for letting me know. Yes. I am responsible for the OGSF.
I will fix it within this week.

Thanks,
Asiyah

**Comment by matentzn** [comment]
Hey! 
For a range of ontology related experiments, I need a current snapshot of the entire OBO foundry ontology repository. I just tried downloading them all manually (from http://www.obofoundry.org/, except the obsolete ones), which resulted in 119 successful downloads. However, 28 failed, which are these ones:

xl.owl
vt.owl
tto.owl
trans.owl 
tgma.owl 
tads.owl 
symp.owl 
sep.owl
sbo.owl 
pdro.owl 
ontoneo.owl 
egsf.owl
OGI.owl 
ogg.owl 
ncit.owl 
miro.owl 
mirnao.owl 
idomal.owl 
fix.owl 
exo.owl 
epidemiology_ontology.owl 
DINTO.owl
ddanat.owl 
emf.owl 
eheminf.owl 
el.owl 
earo.owl
bto.owl

Is there a way I can get an up to date dump as a zip file including all of them? Is tried chasing down the ontologies using their project links, but failed with the first three attempts, so I though I might as well ask here.

**Comment by cmungall** [comment]
Hi, we recently made a change in how we distribute some of the ontologies:

https://github.com/OBOFoundry/purl.obolibrary.org/issues/261

The change went successfully, but it uncovered a hidden issue. For many ontologies the central build was failing, and what was being retrieved may have been a stale copy. This mostly applies to ontologies that are semi-abandoned. However, there are active ontologies like ddanat that are failing, and we will attend to these first (https://github.com/OBOFoundry/purl.obolibrary.org/issues/266).

I note your list contains some ontologies that are not officially registered with OBO - for example OGI. In some cases you have the case wrong (e.g DINTO should be dinto)

OBO-tech people:

This is all documented in http://obofoundry.org/faq/what-is-the-build-field.html

The way to vet this is to look at the log output from the simple obo build job

For convenience, this can be done as

```
make jenkins-output.txt
```

in this repo. The most common cause of error here is a source obo file that does not declare an ontology tag. We must inject this, see:

```
build:
  source_url: ftp://ftp.informatics.jax.org/pub/reports/adult_mouse_anatomy.obo
  method: obo2owl
  infallible: 1
  insert_ontology_id: true
```

**Comment by cmungall** [comment]
But really we should be pushing more groups to take control of their builds. Unfortuately a lot of important ontologies are released by their maintainers as simple obo files made with OE

**Comment by matentzn** [comment]
Hey Chris, thanks for that. The DINTO download button for example does not even point to a file: It points to a GitHub repo home (https://github.com/labda/DINTO). And with respect to OGI, perhaps you are thinking about an ontology with the same id, but there is definitely something here: http://www.obofoundry.org/ontology/ogi.html

Just to be plain, is there a chance I can get these 28 ontologies somehow with a bit or URL hacking (trying the old berkeleybob etc), or is it best I wait until the issues are resolved? I need as much of the OBO foundry as I can get until Wednesday next week. What I dont have by then, I will simply ignore for the experiment. Cheers.

**Comment by cmungall** [comment]
OGI - ah yes, I was getting confused with OGG.

OK, if you want a quick hack by wednesday, then for any failed PURL, try getting it from the old http://www.berkeleybop.org/ontologies/

**Comment by matentzn** [comment]
Perfect, thanks!

**Comment by cmungall** [comment]
I started working through the list.

 * [ ] xl.owl - No such ontology http://obofoundry.org/ontology/xl.html
 * [ ] vt.owl 
 * [ ] tto.owl
 * [ ] trans.owl - source is invalid SF URL. https://github.com/OBOFoundry/OBOFoundry.github.io/issues/343
 * [ ] tgma.owl
 * [ ] tads.owl
 * [ ] symp.owl
 * [ ] sep.owl
 * [ ] sbo.owl
 * [ ] pdro.owl
 * [ ] ontoneo.owl - has never worked, https://github.com/OBOFoundry/OBOFoundry.github.io/issues/341
 * [ ] egsf.owl - no such ontology.
 * [ ] OGI.owl - (should be lowercase). googlecode.
 * [ ] ogg.owl - googlecode.
 * [ ] ncit.owl
 * [ ] miro.owl - source does not resolve - http://anobase.vectorbase.org/miro/miro_release.obo
 * [ ] mirnao.owl - googlecode
 * [ ] idomal.owl
 * [ ] fix.owl
 * [ ] exo.owl
 * [ ] epidemiology_ontology.owl
 * [ ] DINTO.owl - AFAICT has never worked. Known issue: https://github.com/labda/DINTO/issues/1
 * [ ] ddanat.owl - https://github.com/dictyBase/migration-data/issues/6
 * [ ] emf.owl
 * [ ] eheminf.owl - (you mean cheminf?) googlecode.
 * [ ] el.owl - no such ontology
 * [ ] earo.owl - no such ontology
 * [ ] bto.owl - not open. Not clear we have permission to reproduce.


See this ticket https://github.com/OBOFoundry/OBOFoundry.github.io/issues/76 on migrating ontologies from googlecode and sourceforge. It looks like despite repeated prodding a number of ontologies have failed to move

**Comment by TomConlin** [comment]
@cmungall 
starting a new monarch release,  our jenkins job `load-scigraph-ontology-on-dev`
fails with  

    ....
    WARNING: Failed to load ontology: http://purl.obolibrary.org/obo/upheno/monarch.owl  
    org.semanticweb.owlapi.model.UnloadableImportException:   
    Could not load imported     ontology: <http://purl.obolibrary.org/obo/upheno/metazoa.owl>   
    Cause: Could not load imported ontology: <http://purl.obolibrary.org/obo/upheno/vertebrate.owl>   
    Cause: Could not load imported ontology: <http://purl.obolibrary.org/obo/vt.owl>   
    Cause: http://ontologies.berkeleybop.org/vt.owl
	at  ...


http://ci.monarchinitiative.org/view/dev/job/load-scigraph-ontology-on-dev/lastBuild/console

**Comment by matentzn** [comment]
Hey, here a revised list of the few in question. (Sorry for the typos before, I copied them from an unreadable download log of chrome) 

 xl.owl - id: xl, name: Cross-linker reagents ontology, home: http://www.psidev.info/groups/controlled-vocabularies
 egsf.owl -> http://www.obofoundry.org/ontology/ogsf.html
 epidemiology_ontology.owl -- does not exist (id: epo, http://www.obofoundry.org/ontology/epo.html, download https://epidemiology-ontology.googlecode.com/files/epidemiology_ontology.owl does not resolve.
 eheminf.owl - (you mean cheminf? YES) googlecode. Download does not resolve.
 el.owl - no such ontology : SHOULD BE ceph.owl (id: ceph, name: Cephalopod Ontology, http://www.obofoundry.org/ontology/ceph.html, Download does not resolve). 
 earo.owl - no such ontology: SHOULD be caro, Common Anatomy Reference Ontology, Download does not resolve (not allowed) , http://ontologies.berkeleybop.org/caro.owl

**Comment by cmungall** [comment]
ceph and caro fixed

**Comment by matentzn** [comment]
Update there are now only 24 ontologies with broken PURLs: out of those, 13 can be found on the old berkleybob pages, but the purl points to a NoSuchKey Error message. The remaining 11 have no listing on the old berkleybob pages, and mostly fail because of googlecode. However, at least four (dinto, cheminf, ogsf, pdro) should be super easliy fixable by redirecting the purl to github (they all have github repos). xl clearly does not exist (not even a OBO home page) and should be removed from the foundry web site listing (or at least made obsolete).

Berkleybob (13): All have NoSuchKey errors, but are available from the old berkleybob pages.
 tto - NoSuchKey - #345
 trans - NoSuchKey #343
 tgma - NoSuchKey #346
 tads - NoSuchKey #346
 symp - NoSuchKey
 sep - NoSuchKey
 sbo - NoSuchKey #351
 miro - NoSuchKey 
 idomal - NoSuchKey #346
 fix - NoSuchKey
 exo - NoSuchKey 
 ddanat - NoSuchKey 
 bto - NoSuchKey (not open. Not clear we have permission to reproduce)
 
Not on berkleybob / PURL does not resolve 404 (11):
 xl - 404, http://obofoundry.org/ontology/xl.html - DELETE FROM LISTING
 pdro - ontology exists, but PURL unresolved (http://www.obofoundry.org/ontology/pdro.html) #342 (Should be easy though as home link points to github which has the ontology clearly there)
 ontoneo - ontology exists, http://www.obofoundry.org/ontoneo.com, has never worked, #341
 ogsf - ontology exists, refs to old googlecode, purl does not resolve. Interestingly, there is a PURL purl.bioontology.org/ontology/OGSF which points to BioPortal. From their newer github repository, I beleive the purl should point to https://raw.githubusercontent.com/linikujp/OGSF/master/src/ogsf-merged.owl, which can be read here: 
 ogi - ontology exists, googlecode repo, not GitHub, AberOWL and Ontobee copies are there.
 ncit - ontology exists, special case - #348
 mirnao - ontology exists, googlecode
 epo -- ontology exists, googlecode
 DINTO.owl - ontology exists, purl does not resolve. Github repo exists: https://github.com/labda/DINTO/blob/master/DINTO1.2/DINTO_1.2.owl.zip, but ontolgy disseminated as many files in zip. Known issue: labda/DINTO#1
 cheminf.owl - ontology exists,googlecode purl, but GitHub repo exists. Redirect PURL! https://github.com/egonw/semanticchemistry
 cmf.owl - ontology exists, googlecode repo.

**Comment by cmungall** [comment]
On 5 Dec 2016, at 3:55, matentzn wrote:

> xl - 404, <http://obofoundry.org/ontology/xl.html> \- DELETE FROM 
> LISTING

I have found the source of this oddity

ontologies/xmlmod.md:

```
id: xl
label: XL
description: A structured controlled vocabulary for cross-linking 
reagents used with proteomics mass spectrometry.
```

the fileame should always match the idspace. We need a check for this

btw, it's berkeleybop.org (not bob)

**Comment by lschriml** [comment]
I have updated the Transmission Process and Symptom Ontology URLs to their GitHub sites. 
Cheers,
Lynn

**Comment by matentzn** [comment]
Still broken links as of today:

rnao
sep

**Comment by cmungall** [comment]
goodness, sep is still on googlecode, I thought all the PSI ontologies 
had been moved across, I'll follow up, and look into rnao too

**Comment by matentzn** [comment]
I produced another OBO dump today. Out of 154 downloadable ontologies on the 24th April 2017,
142 were downloadable by purl.

The following twelve were not:

**Old berkleybob references (8)**
bto: http://ontologies.berkeleybop.org/bto.owl
exo: http://ontologies.berkeleybop.org/exo.owl
fix: http://ontologies.berkeleybop.org/fix.owl
idomal: http://ontologies.berkeleybop.org/idomal.owl
miro: http://ontologies.berkeleybop.org/miro.owl
sep: http://ontologies.berkeleybop.org/sep.owl
tads: http://ontologies.berkeleybop.org/tads.owl
tgma: http://ontologies.berkeleybop.org/tgma.owl

**Still hosted on Googlecode (4)**
epo: https://epidemiology-ontology.googlecode.com/files/epidemiology_ontology.owl
mirnao: http://mirna-ontology.googlecode.com/svn/trunk/src/ontology/mirnao.owl
ogi: https://ontology-for-genetic-interval.googlecode.com/svn/trunk/src/OGI.owl
ogsf: https://ogsf.googlecode.com/svn/trunk/src/ogsf.owl

**Comment by cmungall** [comment]
cc @graybeal

**Comment by jvendetti** [comment]
I encountered a broken PURL for:

dpo: http://purl.obolibrary.org/obo/dpo.owl

... which didn't seem to be mentioned yet in comments above. 

Also, xl is marked as fixed in [a comment above](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/257#issuecomment-264242016), but the [xl page](http://obofoundry.org/ontology/xl.html) results in a 404 error, and the PURL is broken: http://purl.obolibrary.org/obo/xl.owl

**Comment by matentzn** [comment]
I produced another OBO Foundry dump today!
156 ontologies listed
143 downloadable
13 (12) broken:

404 - Not found (2):
http://purl.obolibrary.org/obo/eo.owl (404-Not found)
http://purl.obolibrary.org/obo/ecocore.owl (404-Not found)

Berkleybob, no such key (6)
http://purl.obolibrary.org/obo/idomal.owl
http://purl.obolibrary.org/obo/tads.owl
http://purl.obolibrary.org/obo/bto.owl
http://purl.obolibrary.org/obo/sep.owl
http://purl.obolibrary.org/obo/miro.owl
http://purl.obolibrary.org/obo/tgma.owl

Googlecode (4)
http://purl.obolibrary.org/obo/ogi.owl (googlecode)
http://purl.obolibrary.org/obo/epo.owl (googlecode)
http://purl.obolibrary.org/obo/ogsf.owl (googlecode)
http://purl.obolibrary.org/obo/mirnao.owl (googlecode)

**Works manually**
Works if you try to download it manually, but it is not easy downloadable programmatically (SSL issue?)
http://purl.obolibrary.org/obo/mamo.owl 

`(sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
`
