### ISSUE TITLE
Make sure all non-downloadable ontologies are marked obsolete

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#546]
This replaces https://github.com/OBOFoundry/OBOFoundry.github.io/issues/257#issuecomment-264242016

I started working through the list; consolidated with @weasteam's list

 * [x] xl.owl - now xlmod.owl, fixed here #284 
 * [ ] vt.owl 
 * [x] tto.owl - incorrect header - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/345
 * [x] trans.owl - source is invalid SF URL. #343 https://github.com/OBOFoundry/OBOFoundry.github.io/issues/343
 * [ ] tgma.owl - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/346
 * [x] tads.owl - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/346
 * [x] symp.owl #343
 * [ ] sep.owl - https://github.com/HUPO-PSI/gelml/issues/1
 * [x] sbo.owl - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/351
 * [x] pdro.owl - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/342
 * [x] ontoneo.owl - has never worked, https://github.com/OBOFoundry/OBOFoundry.github.io/issues/341
 * [ ] ogsf.owl - 
 * [ ] ogi.owl - (should be lowercase). googlecode.
 * [ ] ogg.owl - googlecode. https://github.com/OBOFoundry/OBOFoundry.github.io/issues/347
 * [x] ncit.owl - special case - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/348
 * [ ] miro.owl - source does not resolve - http://anobase.vectorbase.org/miro/miro_release.obo #346
 * [ ] mirnao.owl - googlecode - #789
 * [x] idomal.owl - https://github.com/OBOFoundry/OBOFoundry.github.io/issues/346
 * [ ] fix.owl - #470 #471 
 * [ ] exo.owl - https://github.com/CTDbase/exposure-ontology-draft/issues/4
 * [x] epidemiology_ontology.owl -- does not exist
 * [ ] DINTO.owl - AFAICT has never worked. Known issue: https://github.com/labda/DINTO/issues/1
 * [x] ddanat.owl - #383 (propagates in < 24 hours)
 * [x] emf.owl - no such ontology
 * [x] cheminf.owl - #382, #257
 * [x] el.owl - no such ontology
 * [x] earo.owl - no such ontology
 * [x] bto.owl - not open. Not clear we have permission to reproduce.  #381, #257
 * [x] http://purl.obolibrary.org/obo/mp.owl - https://github.com/OBOFoundry/purl.obolibrary.org/pull/300
 * [ ] http://purl.obolibrary.org/obo/epo.owl #790

See this ticket https://github.com/OBOFoundry/OBOFoundry.github.io/issues/76 on migrating ontologies from googlecode and sourceforge. It looks like despite repeated prodding a number of ontologies have failed to move

**Comment by matentzn** [comment]
Todays attempt to download everything that is not obsolete, these failed:
- bto.owl
- idomal.owl
- mirnao.owl
- miro.owl
- ogi.owl
- ogsf.owl
- sep.owl
- tads.owl
- tgma.owl

**Comment by matentzn** [comment]
These ones also dont work:
- rnao (wrong redirect to berkleybob)
- sepio (wrong redirect to berkleybob)
- xlmod (wrong redirect to berkleybob)
- nomen (wrong redirect to berkleybob)

**Comment by balhoff** [comment]
NOMEN was recently added and still needs a redirect configuration added: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/816

cc @mjy

**Comment by rvita** [comment]
sep has been deemed obsolete. I will continue working on the others.

**Comment by nlharris** [comment]
How is this going, @rvita?

**Comment by nlharris** [comment]
Is this ticket still active or has it been subsumed by others, such as #344 ?

**Comment by matentzn** [comment]
This can be closed! We have all done a lot of work to fix this :D There is one remaining case, but I put it on the agenda for tomorrow! 

https://github.com/HUPO-PSI/mzIdentML/issues/117
